//modded
modded class Land_House_1W03                     { override bool IsRentableHouse() {return true;} };
modded class Land_House_1W05                     { override bool IsRentableHouse() {return true;} };
modded class Land_House_1W06                     { override bool IsRentableHouse() {return true;} };
modded class Land_House_1W08                     { override bool IsRentableHouse() {return true;} };
modded class Land_House_1W10                     { override bool IsRentableHouse() {return true;} };
modded class Land_House_2W02                     { override bool IsRentableHouse() {return true;} };

//modded======================================
class Land_House_1W01 :             BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_House_1W02 :             BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_House_1W03 :             BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_House_1W04 :             BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_House_1W05 :             BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_House_1W06 :             BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_House_1W07 :             BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_House_1W08 :             BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_House_1W09 :             BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_House_1W10 :             BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_House_1W11 :             BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_House_1W12 :             BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_House_2B01 :             BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_House_2B02 :             BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_House_2B03 :             BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_House_2B04 :             BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_House_2W01 :             BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_House_2W02 :             BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_House_2W03 :             BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_House_2W04 :             BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Tenement_Big :           BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Tenement_Small :         BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_City_Store :             BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_City_Store_With_Stairs : BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Village_Store :          BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Village_Store_Enoch :    BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_1F_Corner :   BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_1F1 :         BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_1F2 :         BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_1F3 :         BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_1F4 :         BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_2F_Corner :   BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_2F1 :         BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_2F2 :         BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_2F3 :         BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_2F4 :         BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_2F5 :         BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_2F6 :         BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_2F7 :         BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_2F8 :         BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_2F9 :         BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_3F_Corner :   BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_3F1 :         BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_3F2 :         BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_5F :          BuildingBase { override bool IsRentableHouse() {return true;} };