//modded
modded class Land_House_1W01                     { override bool IsRentableHouse() {return true;} };
modded class Land_House_1W02                     { override bool IsRentableHouse() {return true;} };
modded class Land_House_1W03                     { override bool IsRentableHouse() {return true;} };
modded class Land_House_1W04                     { override bool IsRentableHouse() {return true;} };
modded class Land_House_1W05                     { override bool IsRentableHouse() {return true;} };
modded class Land_House_1W06                     { override bool IsRentableHouse() {return true;} };
modded class Land_House_1W08                     { override bool IsRentableHouse() {return true;} };
modded class Land_House_1W09                     { override bool IsRentableHouse() {return true;} };
modded class Land_House_1W10                     { override bool IsRentableHouse() {return true;} };
modded class Land_House_1W11                     { override bool IsRentableHouse() {return true;} };
modded class Land_House_1W12                     { override bool IsRentableHouse() {return true;} };
modded class Land_House_2W01                     { override bool IsRentableHouse() {return true;} };
modded class Land_House_2W02                     { override bool IsRentableHouse() {return true;} };
modded class Land_House_2B01                     { override bool IsRentableHouse() {return true;} };
modded class Land_HouseBlock_1F1                 { override bool IsRentableHouse() {return true;} };
modded class Land_HouseBlock_1F3                 { override bool IsRentableHouse() {return true;} };
modded class Land_HouseBlock_1F4                 { override bool IsRentableHouse() {return true;} };
modded class Land_HouseBlock_2F1                 { override bool IsRentableHouse() {return true;} };
modded class Land_HouseBlock_2F8                 { override bool IsRentableHouse() {return true;} };
modded class Land_HouseBlock_2F9                 { override bool IsRentableHouse() {return true;} };
modded class Land_HouseBlock_3F2                 { override bool IsRentableHouse() {return true;} };
modded class Land_HouseBlock_5F                  { override bool IsRentableHouse() {return true;} };

//modded======================================
class Land_House_1W07 :             BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_House_2B02 :             BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_House_2B03 :             BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_House_2B04 :             BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_House_2W03 :             BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_House_2W04 :             BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Tenement_Big :           BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Tenement_Small :         BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_City_Store :             BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_City_Store_With_Stairs : BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Village_Store :          BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Village_Store_Enoch :    BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_1F_Corner :   BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_1F2 :         BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_2F_Corner :   BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_2F2 :         BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_2F3 :         BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_2F4 :         BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_2F5 :         BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_2F6 :         BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_2F7 :         BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_3F_Corner :   BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock_3F1 :         BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock3F_Corner1 :   BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_HouseBlock3F_Corner2 :   BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_City_School :   			BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_BusStop_City :   		BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_City_FireStation :   	BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_City_Stand_FastFood :   	BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_City_Stand_Grocery :   	BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_City_Stand_News1 :   	BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_City_Stand_News2 :   	BuildingBase { override bool IsRentableHouse() {return true;} };

class Land_Slum_House1 :   			BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Slum_House2:   			BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Slum_House3:   			BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Slum_House4:   			BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Slum_House5:   			BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Slum_House6:  		 	BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Slum_House7:  		 	BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Shed_M1:   				BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Shed_M3:   				BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Shed_M4:   				BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Shed_W1:   				BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Shed_W2:   				BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Shed_W3:   				BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Shed_W4:   				BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Shed_W5:   				BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Shed_W6:   				BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Tisy_KitchenRoom:   		BuildingBase { override bool IsRentableHouse() {return true;} };

class Land_CementWorks_Hall2_Grey:   	BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_CementWorks_Hall2_Brick:   	BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Village_HealthCare_Enoch:   	BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Shed_Closed:   				BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Garage_Office:   			BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Garage_Row_Big:   			BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_CementWorks_MillB:   		BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Garage_Tall:   				BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Workshop1:   				BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Workshop2:   				BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Workshop3:   				BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Workshop4:   				BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Workshop5:   				BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_Workshop_FuelStation:   		BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_CementWorks_ExpeditionA:     BuildingBase { override bool IsRentableHouse() {return true;} };
class Land_CementWorks_MillC:           BuildingBase { override bool IsRentableHouse() {return true;} };