enum QRPC
{
    //Server -> Client
    SEND_NPC_DATA = 2934152,
	SEND_QUESTS_DATA,
	SEND_SYNC_QUEST,

	//Client -> Server
	REQUEST_GIVE_ITEMS,
	REQUEST_DELIVERY_ITEMS,
	REQUEST_SYNC_DATA,
	REQUEST_SPAWN_ITEM,
	REQUEST_TELEPORT_PLAYER,
}