enum BASTRPC{
	RPC_START = -65446149,

	RPC_SERVER_GETSERVERARRAY,
	RPC_SERVER_GETBUILDING,
	RPC_SERVER_SETPASSCODE,
	RPC_SERVER_ENTERPASSCODE,

	RPC_CLIENT_SYNCHBUILDING,
	RPC_CLIENT_REMOVEBUILDING,
	RPC_CLIENT_REMOVEDOOR,
	RPC_CLIENT_ADDDOOR,
	RPC_CLIENT_PASSCODEERROR,
	RPC_CLIENT_CLOSEMENU,
	RPC_CLIENT_ADDCLIENTTODOOR,
	RPC_CLIENT_CLEARDOORPLAYERARRAY,
	RPC_CLIENT_SHOWSETCODEUI
}

enum BSTMenu {
	SET_CODE_MENU = 17721111,
	GUEST_CODE_MENU
}