enum MultiCharRPC {
	// Server RPCs
	SERVER_GRAB_LOADOUTS = 9726511,

	// Client RPCs
	CLIENT_GRAB_LOADOUTS,
	CLIENT_SHOW_MENU,
	CLIENT_SPAWN_MAG,
	CLIENT_DISCONNECT
}

enum MultiCharMenu {
	MENU_WAIT,
	MENU_SPAWN,
	MENU_CHAR_SELECT
}