enum MultiCharRPC {
	// Server RPCs
	SERVER_GRAB_LOADOUTS = -5165189,
	SERVER_INIT_CLIENT,

	// Client RPCs
	CLIENT_GRAB_LOADOUTS,
	CLIENT_SHOW_MENU,
	CLIENT_SPAWN_MAG,
	CLIENT_DISCONNECT,
	CLIENT_FINISH_INITIALIZATION
}

enum MultiCharMenu {
	MENU_SPAWN
}