enum BST_BankRPC {
    // Server RPC
    SERVER_GRAB_ACCOUNT = -123938,
    SERVER_DEPOSIT_FUNDS,
    SERVER_WITHDRAW_FUNDS,
    SERVER_TRANSFER_FUNDS,

    // Client RPC
    CLIENT_RECEIVE_ACCOUNT,
    CLIENT_RECEIVE_CONFIG
}