enum BSTBankRPC {
    RPC_SERVER_DEPOSIT = 847651,
    RPC_SERVER_WITHDRAW,
    RPC_SERVER_TRANSFER,
    RPC_SERVER_REGISTERACCOUNT,
    RPC_SERVER_ACCOUNTLOGIN,
    RPC_SERVER_ACCOUNTLOGOUT,
    RPC_SERVER_GETBALANCE,

    RPC_CLIENT_ERROR,
}