class BST_CraftingConfig {
    // How to do categories? Set it on the item? Or create a category object which holds the recipe?
    // Really not sure, it'll only be needed for the client. the server won't have to care about it...
    // Also, how to make collapsable categories? Idk, scripting UI's is annoying...
    
}