enum HRPC
{
	SEND_HOUSE_DATA = -074087,
	SEND_ADMINS_ID,

	REQUEST_HOUSE_DATA,
	REQUEST_ADD_HOUSE_INFO,
	REQUEST_RENT_HOUSE,
	REQUEST_APPROVAL_LEASE,
	REQUEST_EVICT_PLAYER,
	REQUEST_ADD_DOOR_GUEST,
	REQUEST_REMOVE_REQUEST,
	REQUEST_EDIT_DOOR_INFO,
	REQUEST_ADD_GUEST_TO_DOOR,
	REQUEST_CANCEL_LEASE,
	REQUEST_ADD_NEW_GROUP,
	REQUEST_EDIT_GROUP_INFO,
	REQUEST_DELETE_GROUP,
}

//923709972
//-2147393536