enum MultiCharRPC {
	// Server RPCs
	SERVER_GRAB_LOADOUTS = -5165189,
	SERVER_INIT_CLIENT,
	SERVER_SPAWN_CLIENT,

	// Client RPCs
	CLIENT_GRAB_LOADOUTS,
	CLIENT_SHOW_MENU,
	CLIENT_SPAWN_MAG,
	CLIENT_DISCONNECT,
	CLIENT_FINISH_INITIALIZATION,
	CLIENT_RECEIVE_PLAYER_API_DATA
}

enum BastionClasses {
	A = 1,
	B,
	C,
	D,
	S
}