enum BST_DTACRPC {
    CLIENT_ADD_GROUP_MEMBER = 92837616,
    CLIENT_REMOVE_GROUP_MEMBER,
    CLIENT_RECEIVE_ACTIVE_GROUP,
    CLIENT_RECEIVE_GROUPS,
    CLIENT_RECEIVE_PLAYER_STAT_UPDATE,
    CLIENT_LEAVE_GROUP,

    SERVER_SEND_GROUP_ARRAY,
    SERVER_JOIN_GROUP,
    SERVER_LEAVE_GROUP
}